### ISSUE TITLE
Failed to run generateChangelog task

### ISSUE THREAD

**Issue by yooksi** [joffrey-bion/gradle-github-changelog#28]
Running task on Gradle `6.7.1`

* What went wrong:
Execution failed for task ':generateChangelog'.
> kotlin.jvm.internal.FunctionReferenceImpl.<init>(ILjava/lang/Object;Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;I)V

* Exception is:
```
Caused by: java.lang.NoSuchMethodError: kotlin.jvm.internal.FunctionReferenceImpl.<init>(ILjava/lang/Object;Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;I)V

        at org.hildan.github.changelog.formatter.MarkdownFormatter$formatReleases$1.<init>(MarkdownFormatter.kt)
        at org.hildan.github.changelog.formatter.MarkdownFormatter.formatReleases(MarkdownFormatter.kt:22)
        at org.hildan.github.changelog.formatter.MarkdownFormatter.formatChangeLog(MarkdownFormatter.kt:17)
        at org.hildan.github.changelog.GitHubChangeLogGenerator.generate(GitHubChangeLogGenerator.kt:23)
        at org.hildan.github.changelog.plugin.GenerateChangelogTask.generate(GitHubChangelogPlugin.kt:33)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
```

**Comment by joffrey-bion** [comment]
Hey, thanks for reporting this. Which version of gradle-github-changelog are you using?
Do you have the same issue with a previous version?

**Comment by yooksi** [comment]
I am using the latest version of the plugin (`1.3.0`).

I have just upgraded to Gradle `v6.8.2` and the plugin is no longer throwing an exception, however the task execution now hangs seemingly indefinitely - currently looking at 5 minutes execution time and counting up.

Any idea what might be causing this issue now?

**Comment by joffrey-bion** [comment]
This is strange. I never faced this.

Are you providing `githubToken` (making logged in requests), or are you using it non-logged in?
I know there is some rate-limiting on GitHub side for non-logged in requests.

**Comment by joffrey-bion** [comment]
Closing this issue as solved. The second issue is trackere here: https://github.com/joffrey-bion/gradle-github-changelog/issues/29
